apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:QqeDfRrWiqpA4mh699welQDY58GnRSyA+r5Bipg3d5qYsMw9r5/NK06QicUClBlqJ0HK1UU=,iv:kBawsSrnXRFORduDsOrt2mW7voqu9pJ2VKuPabFbv8g=,tag:4m5A0zkmoMfC5qNE1FbyMA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPeHZRRFkwajBKTGFvSUky
        ZlhMeUYyRFpVSVBZMTRlQWpGWU1ZOHhtOFV3CldieUtLbFZmOStoQjBob0RHOXEz
        b2dzbGFkV0d0ZnVEemFnTDFPRnUrOVkKLS0tIE8xOVFxNWE3V1JqdUg5OFhxV2sv
        Qy8zVnozaHU0Q2tmaXBuODBSYWQxemsKks4gMVk9mtjo6P5/cm9UKGnFF8XW9cIE
        aOOgo12iZxtWZk2zu5JsazJFXAh8LIErfCfOqprXIgSRqGp4jKASeQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1f2sr4cc26sq7l72drfguyutrvu9ekvgzvgxxtuwncqc2t2chw9gsadyzze
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-26T01:51:26Z"
  mac: ENC[AES256_GCM,data:x8FS40ofiQuONvN5xPmZYI5bn9FjIqAkIbOxb1RwtH5zk+pD62CC78Jz+WDHs8XSIEzRr53f7yEUjbtnqFfKTohMCuheRjzB1fUITycFwWokvXsWoc69YfYjP1EIWyj18y7nZpfsY5Kf2A4eMzXDan0ye85BOgU6UQHvWO4sx/I=,iv:Ib7BfOFkUBbg37UfMvbNRG6W5b8OSjl9b8j9DO9EdS8=,tag:cWL7FhWgcKQyLEh1WkVRxQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
