apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:ziW1mxzO9VyA8g==,iv:bdlHgHKoVC5a3TxzC4XbG1F/g76SJgbza4Sqv8k5S2o=,tag:dLnTKjJcsh/A8sBI/giN8Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0ZWx1ZnF4WExiTVJGM0pT
        dkNIbytqNVZJU25YZlhDbHlvRVZpZzdBMmpnClVqVEIxSHZGUDNzUXpiTmlOT1hq
        ZFZZRENLeHJabjY3RDFZMVRLZ2lob3MKLS0tIFBmRHVUbk5uTGY4QmJUV0tCb2dD
        TGRPY2FVOVZ0R1JZSzlXRDUvbUdSY2cKXsxDoP8s43bTHTa/eTQ38nWRoptv5i0j
        0fwA4mgl+xczoU4Y8ubz8e0n64/FjuSDugMKELmsU3CoMK3Vh35y5A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1f2sr4cc26sq7l72drfguyutrvu9ekvgzvgxxtuwncqc2t2chw9gsadyzze
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-26T01:51:26Z"
  mac: ENC[AES256_GCM,data:jzAWQWKhL6XIM/pYNi/j9W0wsGXlnPQCpbemZaRZ5nk6s5n5WdPEdTfgIl4YPCz/M+jL7RobmJZgiuS9rvElqupIZ67h1apq2cGRC9U7M/+pH1HOgrR4JDxXl2g0vxzC7LTee5Erb9Ifkfhp99SUcyOHGu9C4qg845Cy5zdRc6I=,iv:9bBdPSuDHrX7XXpoqqEGiuAdCNO5H0RObx9RASkZRa8=,tag:vUJ8JiKFhQ7ykuxZqzuirw==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
