apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:14NszdIBbCMyOj3RgVo1tXFEeRNUzc6qUinOrZBDFmM=,iv:UQD7Wjgt1GVLnzHlFaMDT34GnbyhR3XUJ7UtZBt2jTY=,tag:vJSoFWp4JRHMgXWj0Ng/FA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4cWZVeGxTdDZaS0JTaTc5
        RmlqcTZwbkgxUWcyZ0RhTVhtRFRxN1R5MXhzCnJOMzMxQTBYTjJjb296Wjl6bHd1
        TE5hSzhQMlQ1RkZ0OTVYbDJxeklTTzgKLS0tIHMvSHViUEVyM3J0cVF6Vm1kUUdF
        UFYzNldUU094MmFMa1pYQ0ZlUUc5SFkKHi55k0o9vG41NTt6xPtKB2kBGfPJ2QLE
        yM61WeJ4vdiHWa0XUq2EhJ/5H271PaiEqjIPBZCDM0m3w+ZazpeYZg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1f2sr4cc26sq7l72drfguyutrvu9ekvgzvgxxtuwncqc2t2chw9gsadyzze
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-26T01:51:26Z"
  mac: ENC[AES256_GCM,data:LiR21IxNEfgxTMeCWdZMewX4gGtuShnYq7DjO5ZohdT0jsCKSCe8Ym/OvUWAiUkdNLx60B3IwrzdGU1arCN0ZxexCjdlf+IJ3kM7kHm/tc0lVZSDWy5eDHywSIUU6DBCjYEfK5Ze4N3xxk6G7HOOYm+rgAuxQA5YDzI/ffLeO3g=,iv:dddh8ZTkAWHbPASZYQPoKpVEjEqTKgH6rP+8SQTkQ7c=,tag:UhoPY7UlMDIFfbF0zNBu5g==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
