apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:h541Q8wBwj20KKmPrIpU9pNvUCk2YGLOnY+5q5FOw6PTgkS/LvzI4HxREJ7U62Q8xPiLLAw/iXdvnQIUtBHqSNGa2XSiKPVQdgBlTnojRmtfL1IR8XYCECEcD328Xm2G+f/7d71sex0RdetJy+Hgu2OZKiyAaKxPJDHedQAk2VBYzVZ8xzrge3LIll9duRCsNbz/tHA/YaxA4AHvOAa5JZpmwzAKLxit4fluhBZY97mBq7Jg,iv:hHJTDZBX2GN6h6gw4XYPpHbf2GHnSR/+a9c4NUnVrDg=,tag:yn5sS6z21N8UNRLTB0OnnQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqNE1BMXh0QjBNa2N2Sk4v
        UmgxOVE0bUlsaHhkWStOd0VMWUJENGg3dkFJCm0xZk93T3FqUS8yZVIybUc1Tjl1
        TTYwcFd0WDByaGlRTHhhWHpldUZNaWcKLS0tIEdOR05teXpobW9tU09aNVovYVNK
        TjI3aDFaUjVSSTlpTXlsS0JUSG5uYncK74hxiyl8kt48gqrxgCeXeLwiSDTSOJn8
        fAmnF6oF9LXV6aXcVex6BGCbLuTEd1gwzgV5xcx2ATGM1wi6aYsGtQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1f2sr4cc26sq7l72drfguyutrvu9ekvgzvgxxtuwncqc2t2chw9gsadyzze
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-26T01:51:26Z"
  mac: ENC[AES256_GCM,data:Bvzd+mrbaK+uEnt+Y2MIa4Q0RQ9nbP9Kt5O1D90Nk9jXJLbJTzg7ZKG79J6eEP5613X/FT+d41IPkZrzWwqS4biGHPqWYxWd9c+TDiiaQ5wXacEMZSDf6InXDP0JGA77bA8xIz/w/UUF9YM3uMzQppmD4xV8AzgGg106A7VVSGg=,iv:RK5mjHaHVRuN9dPmBV7X0mWiFLCrK4nJdWCSWOfyNOs=,tag:Ge+3PWZZ3dOuxNwAdtJaVQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
