---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: adguard-dns
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  refreshInterval: "48h0m0s"
  target:
    name: adguard-configuration
  data:
    - secretKey: user
      remoteRef:
        key: adguard/username
    - secretKey: password
      remoteRef:
        key: adguard/password
