apiVersion: v1
stringData:
  password: ENC[AES256_GCM,data:yj57TPTDPnU=,iv:NQt+HECy2QS/jaZLMeiTvGFJFpLJ7JPbC4RpoY613F0=,tag:qZh0LEyOI6t7F9LH4KNscg==,type:str]
  url: ENC[AES256_GCM,data:toM8aOwABQvoH1OC6Lf0wSiiCg==,iv:PHK40y+/6j63ADxWpSAcMkH0HP3Y6IWDQCo/F7t5puQ=,tag:RUgNOfJGBdDXzxwYJD4E+w==,type:str]
  user: ENC[AES256_GCM,data:Z+mHmQ48,iv:iwmAttj4MnBGMEAe2ovJOTayUe79FMHEpuLnidzBPx4=,tag:pPBB6RB2T6dbMSXzLj6L9A==,type:str]
kind: Secret
metadata:
  name: adguard-configuration
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwNDZBWmc2OFFRZ1E5ZjVr
        SE5sRU5iSmhMMFRtYm9xR0ZSL1ZoVEJUbHcwCjRCWTVINzZrdFQ4TGx2dmVMUHlH
        bUZZaGFkaGxxVTIwLzdPdVZFZFpTMU0KLS0tIHBoUm1IdCtuTEZ3Uk04d2pvZ2Vx
        MjQ3MkNyZGFaSlpiVk4rdjFEYXRsVmcKeRM22veEOXjR+MGl0LqgB6LCrOEx2QUO
        1EDMazBixtVR7kmo6B6BCO0CPN/ypY5lwm0YPpv6HpvxQspjlokJdg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1f2sr4cc26sq7l72drfguyutrvu9ekvgzvgxxtuwncqc2t2chw9gsadyzze
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-27T03:39:11Z"
  mac: ENC[AES256_GCM,data:hF3eZjA0C8lDDqe/0j7TcBP7fyMfTBWC3ylnpayC9eHuXsk7q4wHOo3+1JmtQ3aAdCNIdbtKIYk3vcUaE8uLYW7g9aSHYmlX+quw44uXqXRbuXBr06m1CqX84BIR3T93i+diz60enBikna+eYs7WzQSxmh71AmcSkOuysuu7Wk8=,iv:t6lPE4SnoHp7afpyNXEUvD4bvtu3nkLpMCl9VSZSG6w=,tag:C+Jf5fLg7omIgaoYO7t7tA==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
