---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./clusterissuer.yaml
  - ./helmrelease.yaml
  - ./ocirepository.yaml
  - ./externalSecret.yaml
  - ./grafanadashboard.yaml
  - ./prometheusrule.yaml
