apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:I+zHTrt6f9eguHcL82azu0dBTJAAGmBiK2lh0IaWqhHqQz06xHEksr0FTs7N/PfCa4FkI68=,iv:Ob+h4zUkPkIJsmvZt+Ik/TIOqiqQQiNXvDAP7XNYL3w=,tag:vA0wz6UyL4QnGh+PvGrFaw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLL2xSc3B5b3JCYi82b1Zi
        clRvYm1FSjFOL2xyU3lseEF5Tk1JZmlHeHpNCndYQVJnMVJiem41RjF1OThSSWtW
        NGNrVDMyMlRMYmlUU2JibS9OeElueDgKLS0tIGlsZkdSVGdOdEJtMzVyUGl2YkpY
        OU5Qai9MQUtXdGkxVC9HWVROWmFvV00K1725EoCsogaPMjhajiQdfFItKthj+hka
        HRQPSakyuiUZo+J9ZhFWprLhGHGHtGps13wYvV3QDOZwAjRqJ1Iwng==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1f2sr4cc26sq7l72drfguyutrvu9ekvgzvgxxtuwncqc2t2chw9gsadyzze
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-26T01:51:26Z"
  mac: ENC[AES256_GCM,data:zKvSR39s4AuCMD1bIkK7KXuYS/J5Nb6exC7VymUZ+3Jtr0SAeFM9nvwPHLptamIq8DDMfo8u8b0tMqTxNQRPK07b5vrEkB61ROQZ7LHVXizLJoP3tyxFpzSSAqa6jvfYtxiRHt9n7GZZVHEml5dq7L5YrnY7BoLNGWgglz4pDmk=,iv:gIBrUNGHR8gtKSspioeq2sszOHDAueaUcPNdPfsDzoQ=,tag:kj9i6YL2aXArWCd96g6thQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
