# yaml-language-server: $schema=https://github.com/budimanjojo/talhelper/blob/master/pkg/config/schemas/talconfig.json
---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://192.168.1.10:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "192.168.1.10"
  - "home-cluster.mebays.org"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "pi-kube-1-a"
    ipAddress: "192.168.1.11"
    installDisk: "/dev/sda"
    machineSpec:
      mode: metal
      arch: arm64
      secureboot: false
    schematic: &schematic1
      overlay:
        image: siderolabs/sbc-raspberrypi
        name: rpi_generic
        options:
          configTxtAppend: |-
            dtoverlay=rpi-poe-plus,poe_fan_temp0=50000,dtparam=poe_fan_temp1=60000,dtparam=poe_fan_temp2=70000,dtparam=poe_fan_temp3=80000
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/iscsi-tools
            - siderolabs/nfs-utils
            - siderolabs/util-linux-tools
            - siderolabs/vc4
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "d8:3a:dd:8a:47:f1"
        dhcp: false
        addresses:
          - "192.168.1.11/16"
        routes:
          - gateway: "192.168.0.1"
            network: 0.0.0.0/0
        mtu: 1500
        vip:
          ip: "192.168.1.10"
  - hostname: "pi-kube-1-b"
    ipAddress: "192.168.1.12"
    installDisk: "/dev/sda"
    machineSpec:
      mode: metal
      arch: arm64
      secureboot: false
    schematic: *schematic1
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "d8:3a:dd:8a:48:51"
        dhcp: false
        addresses:
          - "192.168.1.12/16"
        routes:
          - gateway: "192.168.0.1"
            network: 0.0.0.0/0
        mtu: 1500
        vip:
          ip: "192.168.1.10"
  - hostname: "pi-kube-1-c"
    ipAddress: "192.168.1.13"
    installDisk: "/dev/sda"
    machineSpec:
      mode: metal
      arch: arm64
      secureboot: false
    schematic: *schematic1
    controlPlane: false
    volumes: &volumes
      - name: EPHEMERAL
        provisioning:
          maxSize: 100GiB
          grow: false
    userVolumes: &userVolumes
      - name: longhorn
        provisioning:
          diskSelector:
            match: system_disk
          minSize: 800GiB
          maxSize: 800GiB
          grow: false
    patches:
      - &longhorn-node |-
        machine:
          kernel:
            modules:
              # Required by Longhorn's V1 iSCSI frontend.
              - name: iscsi_tcp
          kubelet:
            extraMounts:
              - destination: /var/mnt/longhorn
                type: bind
                source: /var/mnt/longhorn
                options:
                  - bind
                  - rshared
                  - rw
          nodeLabels:
            node.longhorn.io/create-default-disk: "true"
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "d8:3a:dd:8a:4b:29"
        dhcp: false
        addresses:
          - "192.168.1.13/16"
        routes:
          - gateway: "192.168.0.1"
            network: 0.0.0.0/0
        mtu: 1500
  - hostname: "pi-kube-1-d"
    ipAddress: "192.168.1.14"
    installDisk: "/dev/sda"
    machineSpec:
      mode: metal
      arch: arm64
      secureboot: false
    schematic: *schematic1
    controlPlane: false
    volumes: *volumes
    userVolumes: *userVolumes
    patches:
      - *longhorn-node
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "d8:3a:dd:8a:48:61"
        dhcp: false
        addresses:
          - "192.168.1.14/16"
        routes:
          - gateway: "192.168.0.1"
            network: 0.0.0.0/0
        mtu: 1500
  - hostname: "pi-kube-2-a"
    ipAddress: "192.168.1.21"
    installDisk: "/dev/sda"
    machineSpec:
      mode: metal
      arch: arm64
      secureboot: false
    schematic: &schematic2
      overlay:
        image: siderolabs/sbc-raspberrypi
        name: rpi_generic
        options:
          configTxtAppend: |-
            enable_uart=0
            dtparam=i2c_arm=on,i2c_arm=baudrate=400000
            dtparam=i2c1=on
            dtoverlay=gpio-fan,gpiopin=14,temp=60000
            dtoverlay=gpio-shutdown,gpio_pin=4,active_low=1,gpio_pull=up
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/iscsi-tools
            - siderolabs/nfs-utils
            - siderolabs/vc4
            - siderolabs/util-linux-tools
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "2c:cf:67:33:52:a9"
        dhcp: false
        addresses:
          - "192.168.1.21/16"
        routes:
          - gateway: "192.168.0.1"
            network: 0.0.0.0/0
        mtu: 1500
        vip:
          ip: "192.168.1.10"
    patches:
      - |-
        machine:
          nodeLabels:
            org.mebays/rpi-display: true
  - hostname: "pi-kube-2-b"
    ipAddress: "192.168.1.22"
    installDisk: "/dev/sda"
    machineSpec:
      mode: metal
      arch: arm64
      secureboot: false
    schematic: *schematic2
    controlPlane: false
    volumes: *volumes
    userVolumes: *userVolumes
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "d8:3a:dd:6e:87:9a"
        dhcp: false
        addresses:
          - "192.168.1.22/16"
        routes:
          - gateway: "192.168.0.1"
            network: 0.0.0.0/0
        mtu: 1500
    patches:
      - *longhorn-node
      - |-
        machine:
          nodeLabels:
            org.mebays/rpi-display: true
  - hostname: "pi-kube-2-c"
    ipAddress: "192.168.1.23"
    installDisk: "/dev/sda"
    machineSpec:
      mode: metal
      arch: arm64
      secureboot: false
    schematic: *schematic2
    controlPlane: false
    volumes: *volumes
    userVolumes: *userVolumes
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "2c:cf:67:33:56:41"
        dhcp: false
        addresses:
          - "192.168.1.23/16"
        routes:
          - gateway: "192.168.0.1"
            network: 0.0.0.0/0
        mtu: 1500
    patches:
      - *longhorn-node
      - |-
        machine:
          nodeLabels:
            org.mebays/rpi-display: true
  - hostname: "pi-kube-2-d"
    ipAddress: "192.168.1.24"
    installDisk: "/dev/sda"
    machineSpec:
      mode: metal
      arch: arm64
      secureboot: false
    schematic: *schematic2
    controlPlane: false
    volumes: *volumes
    userVolumes: *userVolumes
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "2c:cf:67:33:55:ec"
        dhcp: false
        addresses:
          - "192.168.1.24/16"
        routes:
          - gateway: "192.168.0.1"
            network: 0.0.0.0/0
        mtu: 1500
    patches:
      - *longhorn-node
      - |-
        machine:
          nodeLabels:
            org.mebays/rpi-display: true

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/cluster.yaml"
